### ISSUE TITLE
Write Access

### ISSUE THREAD

**Issue by Tommsy64** [dirty-mechanics-3932/2016Robot#4]
May I have **write access** for pushing a pull-request branch?

**Comment by adamzg** [comment]
Hi Tommsy64, 

Could you please provide your full name and who you've been working with at Dirty Mechanics so I can verify your access level requirements with them?

Thanks.

**Comment by bassile** [comment]
Hello Thomas
We are all here waiting at the robotics room.

Sent from my iPhone
Chief Information Officer
Saint Andrews School
Boca Raton, Florida

On Jul 6, 2016, at 11:44 PM, Thomas notifications@github.com wrote:

May I have _write access_ for pushing a pull-request branch?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/dirty-mechanics-3932/2016Robot/issues/4, or mute the
thread
https://github.com/notifications/unsubscribe/AP20ouAJZkfpRy4I8yYXQ_YOcPlDbFCZks5qTHYYgaJpZM4JGth5
.
